; PlatformIO Project Configuration
; https://docs.platformio.org/en/latest/projectconf/

[platformio]
src_dir = DengFOC_Knob

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM12
