[project]
name = "easyknob-root"
version = "0.1.0"
description = "EasyKnob - force feedback knob for EasyTeleop"
requires-python = ">=3.10"
dependencies = [
    "platformio>=6.1.19",
    "pyserial>=3.5",
    "easyknob",
    "easyknob-gui",
    "easyknob-examples",
]

[tool.uv.workspace]
members = ["easyknob_sdk", "easyknob_gui", "easyknob_examples"]

[tool.uv.sources]
easyknob = { workspace = true }
easyknob-gui = { workspace = true }
easyknob-examples = { workspace = true }
